export { useSpotlight, type SpotlightOptions } from './useSpotlight'
export { useMagnetic, type MagneticOptions } from './useMagnetic'
export { Reveal, type RevealProps } from './Reveal'
export { withViewTransition } from './viewTransition'
export { EASE, REVEAL_DURATION, REVEAL_RISE, REVEAL_STAGGER } from './motion'
